language: java
sudo: false

jdk:
 - oraclejdk8

after_success:
  - mvn clean cobertura:cobertura -Dcobertura.report.format=xml org.eluder.coveralls:coveralls-maven-plugin:3.1.0:report

notifications:
 email: false
